[package]
name = "graphul"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "graphul"

[dependencies]
common = { path = "../common" }

graphul = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }
