[package]
name = "salvo"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "salvo"

[dependencies]
common = { path = "../common" }

salvo = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }
